### ISSUE TITLE
作者您好！可以使用集群模式吗

### ISSUE THREAD

**Issue by Zmmmmy** [490937333/nacos-oracle-2.2.3#1]
作者您好！可以使用集群模式吗

**Comment by 490937333** [comment]
可以的，我没试过 你可以试下，我只是针对oracle 新增了查询sql和对应的java代码，逻辑没动

**Comment by Zmmmmy** [comment]
您好！集群启动没有生效还是单机，这个可以帮忙试一下嘛，有偿！感谢！！！！！

**Comment by 490937333** [comment]
nacos-2.2.3\console\src\main\java\com\alibaba\nacos  这儿的我写死了单机，你下载源码 然后按照我写的去掉下单机就行了
/**
 * Nacos starter.
 *
 * @author nacos
 */
@SpringBootApplication(scanBasePackages = "com.alibaba.nacos")
@ServletComponentScan
@EnableScheduling
public class Nacos {

    public static void main(String[] args) {
        System.setProperty("nacos.standalone", "true");//默认单机
        System.setProperty("server.tomcat.accesslog.enabled", "false");
        SpringApplication.run(Nacos.class, args);
        System.out.println("nacos2.2.3 start 。。。");
    }
}

**Comment by Zmmmmy** [comment]
非常感谢！！！！！！太感谢了！！！！！！！
